import { memo, useState, useCallback } from 'react'
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Alert,
  Typography,
  Box
} from '@mui/material'
import { EntityFormGenerator } from './forms/EntityFormGenerator'
import { useGenericData } from '../context/GenericDataContext'
import { appConfig } from '../data/configurableData'

interface EntityCreateDialogProps {
  entityKey: string
  open: boolean
  onClose: () => void
  onSuccess?: () => void
}

/**
 * EntityCreateDialog Component
 *
 * Generic, reusable dialog for creating new entities.
 * Works with any entity type through configuration.
 *
 * Features:
 * - Schema-driven form rendering
 * - Automatic validation
 * - Error handling
 * - Success callbacks
 *
 * @example
 * ```tsx
 * <EntityCreateDialog
 *   entityKey="todoItem"
 *   open={createDialogOpen}
 *   onClose={() => setCreateDialogOpen(false)}
 *   onSuccess={() => showSuccessMessage()}
 * />
 * ```
 */
export const EntityCreateDialog = memo(({
  entityKey,
  open,
  onClose,
  onSuccess
}: EntityCreateDialogProps) => {
  const { createEntity } = useGenericData()
  const [formData, setFormData] = useState<any>({})
  const [isValid, setIsValid] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Get form schema from config
  const schema = appConfig.formSchemas?.[entityKey]

  const handleClose = useCallback(() => {
    if (!isSubmitting) {
      setFormData({})
      setError(null)
      onClose()
    }
  }, [isSubmitting, onClose])

  const handleSubmit = useCallback(async () => {
    if (!isValid || isSubmitting) return

    setIsSubmitting(true)
    setError(null)

    try {
      // Remove id if present (will be generated by service)
      const { id, ...dataToSubmit } = formData

      await createEntity(entityKey, dataToSubmit)

      // Success
      setFormData({})
      onSuccess?.()
      onClose()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create entity')
    } finally {
      setIsSubmitting(false)
    }
  }, [entityKey, formData, isValid, isSubmitting, createEntity, onSuccess, onClose])

  if (!schema) {
    return (
      <Dialog open={open} onClose={handleClose}>
        <DialogContent>
          <Alert severity="error">
            No form schema configured for entity: {entityKey}
          </Alert>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleClose}>Close</Button>
        </DialogActions>
      </Dialog>
    )
  }

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      maxWidth="sm"
      fullWidth
      PaperProps={{
        component: 'form',
        onSubmit: (e: React.FormEvent) => {
          e.preventDefault()
          handleSubmit()
        }
      }}
    >
      <DialogTitle>
        {schema.title || `Create ${entityKey}`}
      </DialogTitle>

      <DialogContent>
        {schema.description && (
          <Box mb={2}>
            <Typography variant="body2" color="text.secondary">
              {schema.description}
            </Typography>
          </Box>
        )}

        {error && (
          <Alert severity="error" sx={{ mb: 2 }}>
            {error}
          </Alert>
        )}

        <EntityFormGenerator
          entityKey={entityKey}
          schema={schema}
          onChange={setFormData}
          onValidate={setIsValid}
        />
      </DialogContent>

      <DialogActions>
        <Button onClick={handleClose} disabled={isSubmitting}>
          {schema.cancelLabel || 'Cancel'}
        </Button>
        <Button
          type="submit"
          variant="contained"
          disabled={!isValid || isSubmitting}
        >
          {isSubmitting ? 'Creating...' : (schema.submitLabel || 'Create')}
        </Button>
      </DialogActions>
    </Dialog>
  )
})

EntityCreateDialog.displayName = 'EntityCreateDialog'
